In [324]:
import numpy as np
import pandas as pd
pd.set_option('max_columns', 100)

## Recognize internal vs. external

In [347]:
def incoming_outgoing_timings(sent, heard, other_sent):
    l_out = []
    l_in = []
    for i, timing in enumerate(heard):
        has_incoming = min(np.abs(timing - np.array(other_sent))) < 2
        has_outgoing = min(np.abs(timing - np.array(sent))) < 2
        if has_incoming and not has_outgoing:
            l_in.append(timing)
        elif has_outgoing and not has_incoming:
            l_out.append(timing)
    return l_in, l_out
def closest(x, vec):
    res = vec[np.argmin(np.abs(np.array(vec) - x))]
    if abs(res - x) < 1:
        return res
    else:
        return None

In [348]:
def distances(heard1, sent1, heard2, sent2):
    lin1, lout1 = incoming_outgoing_timings(sent1, heard1, sent2)
    lin2, lout2 = incoming_outgoing_timings(sent2, heard2, sent1)
    
    l = []
    for x in sorted(set(lin1)):
        m_in1 = x
        m_out2 = closest(m_in1, lout2)

        if not m_out2:
            continue
        l.append([])
        for y in sorted(lin2):
            n_in2 = y
            n_out1 = closest(n_in2, lout1)
            l[-1].append(-1)
            if not n_out1:
                continue

            distance = ((m_in1 - m_out2) + (n_in2 - n_out1)) * 343 / 2
            l[-1][-1] = distance
    return pd.DataFrame(l, columns=sorted(lin2 - lin2[0]))

## Data

## Sony to Mi5, FRAMES_FOR_SEARCH = 262144 / 2

In [349]:
# Sony
heard1=[77942.98435163498, 77952.04256010056, 77955.5232629776, 77959.05070066452, 77961.56292295456, 77965.10990715027, 77968.70423817635, 77970.1707687378, 77973.80011105537, 77976.22133564949, 77981.25147175789, 77981.25147175789, 77989.28988432884, 78000.35339903831, 78009.35412478447, 78015.43160772324, 78016.45058727264, 78027.48258280754, 78031.5640566349, 78036.50938558578, 78039.76192522049, 78039.76192522049, 78044.56902265549, 78049.8254172802, 78051.60972571373]
sent1=[77942.83100008965, 77951.88499999046, 77958.91499996185, 77964.96000003815, 77970.00900006294, 77976.05599999428, 77981.09200000763, 77989.13000011444, 78000.18400001526, 78009.21399998665, 78016.25999999046, 78027.30900001526, 78036.35199999809, 78044.40300011635, 78051.43899989128]

## MediaPlayer+sleep()
heard1=[816.3925487995148, 826.4467663764954, 840.5190794467926, 852.9041814804077, 855.5509161949158, 859.912752866745, 863.5937504768372, 873.0153152942657, 877.6281723976135, 880.1363356113434, 887.689578294754, 892.3341360092163, 896.7189886569977, 903.3435463905334, 909.7493741512299, 916.4608707427979, 918.7994422912598, 925.8412334918976, 928.6871292591095, 933.9011654853821, 940.7749297618866, 944.9306213855743]
sent1=[816.2420001029968, 826.2909998893738, 840.3359999656677, 855.3780000209808, 863.4240000247955, 877.470999956131, 887.5150001049042, 896.5520000457764, 909.5899999141693, 918.6319999694824, 925.6740000247955, 933.7139999866486, 944.7630000114441]

In [350]:
#Mi5
heard2=[77936.50028800964, 77940.291172266, 77949.34452819824, 77952.81101346016, 77956.35255551338, 77958.85071873665, 77962.41192054749, 77965.99203395844, 77967.4728050232, 77971.08792972565, 77973.52339458466, 77979.28538990021, 77986.59185266495, 77988.39026522636, 77996.53164839745, 77997.65539002419, 78006.74486851692, 78006.74486851692, 78012.71942615509, 78013.75248742104, 78019.8072040081, 78024.78455090523, 78028.85180711746, 78033.81178450584, 78037.04969835281, 78037.04969835281, 78041.86255550385, 78047.11309981346]
sent2=[77936.37800002098, 77945.52300000191, 77952.63700008392, 77958.71099996567, 77965.84699988365, 77970.97000002861, 77979.09999990463, 77988.23000001907, 77996.33500003815, 78006.45399999619, 78012.54800009727, 78019.66499996185, 78028.74799990654, 78036.87599992752, 78046.98000001907]
    
## MediaPlayer+sleep()
heard2=[805.7034785747528, 812.8074014186859, 813.6441133022308, 823.6982402801514, 823.6982402801514, 826.8242268562317, 837.7705080509186, 841.9493060112, 850.1325714588165, 850.1325714588165, 852.8024580478668, 857.139374256134, 860.8451790809631, 870.2438640594482, 874.8795783519745, 877.3630928993225, 884.94105219841, 889.5625033378601, 893.9704852104187, 900.5744309425354, 907.0008254051208, 913.6892380714417, 916.0508027076721, 916.0508027076721, 923.0926394462585, 925.9136371612549, 931.152594089508, 931.152594089508, 938.0016417503357, 942.1819818019867]
sent2=[805.5309998989105, 812.6579999923706, 826.7149999141693, 841.8259999752045, 849.9849998950958, 857.0539999008179, 870.1429998874664, 877.2539999485016, 889.3800001144409, 900.4739999771118, 913.5910000801086, 925.7430000305176, 937.8719999790192]
heard2 = np.array(heard2) + 3
sent2 = np.array(sent2) + 3

In [351]:
distances(heard1, sent1, heard2, sent2)

,0.000000,0.000000,14.072268,29.104218,37.146939,51.181338,61.242812,70.272245,83.302585,92.352562,92.352562,99.394399,107.454354,107.454354,118.483742
0,3.958893,3.958893,3.951124,3.970546,3.951124,3.947240,3.958893,3.962778,3.955009,3.939430,3.939430,3.947240,3.951124,3.951124,3.939430
1,4.262206,4.262206,4.254437,4.273860,4.254437,4.250553,4.262206,4.266091,4.258322,4.242743,4.242743,4.250553,4.254437,4.254437,4.242743
2,3.931661,3.931661,3.923892,3.943315,3.923892,3.920008,3.931661,3.935546,3.927777,3.912198,3.912198,3.920008,3.923892,3.923892,3.912198
3,4.238900,4.238900,4.231131,4.250553,4.231131,4.227246,4.238900,4.242784,4.235015,4.219437,4.219437,4.227246,4.231131,4.231131,4.219437
4,3.962778,3.962778,3.955009,3.974431,3.955009,3.951124,3.962778,3.966662,3.958893,3.943315,3.943315,3.951124,3.955009,3.955009,3.943315
5,3.531074,3.531074,3.523305,3.542727,3.523305,3.519421,3.531074,3.534958,3.527189,3.511611,3.511611,3.519421,3.523305,3.523305,3.511611
6,4.281669,4.281669,4.273900,4.293323,4.273900,4.270016,4.281669,4.285554,4.277785,4.262206,4.262206,4.270016,4.273900,4.273900,4.262206
7,4.246668,4.246668,4.238900,4.258322,4.238900,4.235015,4.246668,4.250553,4.242784,4.227205,4.227205,4.235015,4.238900,4.238900,4.227205

## Sony to Samsung, FRAMES_FOR_SEARCH = 262144 / 2

In [356]:
# Sony
heard1=[82750.40468263626, 82759.08012461662, 82760.41905903816, 82768.1284468174, 82774.14175748825, 82779.60699558258, 82782.19808387756, 82785.77016997337, 82787.2208275795, 82790.85740375519, 82793.29198408127, 82799.94012475014, 82799.94012475014, 82802.33193874359, 82806.00824260712, 82808.35218811035, 82812.13819718361, 82819.3976984024, 82820.21860551834, 82825.28456926346, 82830.41624712944, 82832.34699559212, 82835.48454642296, 82840.45921778679, 82846.50434231758]
sent1=[82758.90799999237, 82767.95700001717, 82773.99300003052, 82782.03500008583, 82787.0759999752, 82793.12700009346, 82802.16199994087, 82808.2049999237, 82819.242000103, 82830.27800011635, 82835.31599998474, 82846.35500001907]

## MediaPlayer + sleep()
heard1=[1650.5637710094452, 1651.9056758880615, 1657.6467869281769, 1663.9484195709229, 1672.755585193634, 1676.0130908489227, 1684.0359251499176, 1684.8250634670258, 1692.904632806778, 1696.09286403656, 1703.1090772151947, 1703.1090772151947, 1705.9814808368683, 1714.1578979492188, 1717.0960838794708, 1723.230256319046, 1727.1948821544647, 1734.2517755031586, 1741.2320249080658, 1749.2903015613556, 1751.283340215683, 1759.390165567398]
sent1=[1651.744999885559, 1663.792000055313, 1675.845999956131, 1683.880000114441, 1695.9260001182556, 1702.9560000896454, 1713.994999885559, 1723.0439999103546, 1734.0880000591278, 1749.1370000839233]

In [357]:
#Samsung
heard2=[82749.52538776398, 82758.2241859436, 82759.5396053791, 82767.68262124062, 82773.28219032288, 82778.72745108604, 82781.3406484127, 82784.89060306549, 82784.89060306549, 82786.35724711418, 82789.97772336006, 82792.42849421501, 82792.42849421501, 82799.06053519249, 82801.47856235504, 82805.12860774994, 82807.47863030434, 82807.49581861496, 82811.2424852848, 82819.33894777298, 82824.40461683273, 82829.55942392349, 82831.46706581116, 82834.62461662292, 82839.5793106556, 82839.5793106556, 82845.64048981667, 82846.6557958126]
sent2=[82749.40499997139, 82759.44400000572, 82767.5529999733, 82778.63199996948, 82784.7460000515, 82789.8599998951, 82798.94799995422, 82805.02500009537, 82811.12800002098, 82819.21499991417, 82824.28999996185, 82831.36400008202, 82839.45700001717, 82846.53800010681]

## MediaPlayer + sleep()
heard2=[1649.6509251594543, 1650.9988615512848, 1656.7338955402374, 1663.0417413711548, 1671.8424670696259, 1675.1064126491547, 1683.9119455814362, 1691.991355895996, 1695.194054365158, 1702.2103807926178, 1705.0682039260864, 1713.251514673233, 1716.1827845573425, 1722.3311972618103, 1726.281310558319, 1726.281310558319, 1733.344485282898, 1740.3102447986603, 1748.3911519050598, 1750.3697233200073, 1758.4765486717224, 1762.4203128814697, 1769.542353630066, 1777.4750974178314, 1780.5626258850098, 1792.507863998413, 1794.6722402572632]
sent2=[1649.5209999084473, 1656.6070001125336, 1671.6970000267029, 1683.7820000648499, 1691.8650000095367, 1704.9489998817444, 1716.0529999732971, 1726.1440000534058, 1740.1900000572205, 1750.2430000305176, 1758.3429999351501, 1769.401999950409, 1780.4560000896454, 1794.5480000972748]
heard2 = np.array(heard2) + 1
sent2 = np.array(sent2) + 1

In [358]:
distances(heard1, sent1, heard2, sent2)

   0.000000   12.064671  32.152313  39.168639  50.209773  59.289456  70.302744
0   1.065562   1.065562   2.415014   2.434437   1.116141   2.372245   0.960600
1   1.104447   1.104447   2.453900   2.473322   1.155026   2.411130   0.999485
2   1.131679   1.131679   2.481132   2.500554   1.182258   2.438362   1.026717
3   1.131679   1.131679   2.481132   2.500554   1.182258   2.438362   1.026717
4   1.135522   1.135522   2.484975   2.504397   1.186102   2.442205   1.030561
5   1.182217   1.182217   2.531670   2.551092   1.232797   2.488900   1.077256
6   2.589978   2.589978   3.939430   3.958852   2.640557   3.896660   2.485016
7   1.189986   1.189986   2.539439   2.558861   1.240566   2.496669   1.085025
8   1.189986   1.189986   2.539439   2.558861   1.240566   2.496669   1.085025

## Mi5 to Samsung, FRAMES_FOR_SEARCH = 262144 / 2

In [359]:
# Mi5
heard1=[83111.09841251373, 83114.86498856544, 83116.22281169891, 83123.96625852585, 83130.02795910835, 83135.4052605629, 83137.17244887352, 83142.20537400246, 83143.51605439186, 83149.33281159401, 83154.61641716957, 83156.39916086197, 83160.69648528099, 83164.53353738785, 83171.78804969788, 83174.57095217705, 83174.57095217705, 83181.88653039932, 83183.64154195786, 83188.95804977417, 83191.81004524231, 83200.10829925537, 83201.89569163322, 83208.17501115799, 83211.01820850372]
sent1=[83114.68700003624, 83123.78699994087, 83129.87700009346, 83137.00200009346, 83142.08500003815, 83149.19899988174, 83156.29099988937, 83164.40100002289, 83174.47000002861, 83183.52500009537, 83191.63400006294, 83201.72600007057, 83210.86599993706]

## MediaPlayer+sleep()
heard1=[1207.664226770401, 1217.471664428711, 1225.560326576233, 1236.6723220348358, 1237.602435350418, 1244.7296917438507, 1250.7536146640778, 1254.8139548301697, 1262.9153606891632, 1265.772458076477, 1265.772458076477, 1273.018149614334, 1279.9793515205383, 1283.0461089611053, 1288.0349297523499, 1291.1562449932098, 1300.2357687950134, 1303.0763130187988, 1310.2667891979218, 1314.197764158249, 1322.4088072776794, 1328.273954629898, 1337.4951112270355, 1342.364045381546, 1347.5266530513763, 1357.44105219841]
sent1=[1217.2669999599457, 1225.3949999809265, 1237.454999923706, 1250.5739998817444, 1265.651999950409, 1279.7809998989105, 1287.8689999580383, 1302.9230000972748, 1314.069000005722, 1328.1340000629425, 1342.2039999961853, 1357.3139998912811]

In [360]:
#Samsung
heard2=[83112.9550793171, 83116.72671198845, 83118.07954645157, 83126.12877559662, 83131.88945579529, 83137.26190471649, 83139.03403615952, 83144.06696152687, 83145.3725168705, 83145.3725168705, 83156.47294783592, 83158.26063489914, 83162.5529024601, 83166.39496588707, 83173.64437651634, 83173.64437651634, 83176.43240356445, 83183.74269843102, 83185.50283455849, 83190.81433105469, 83193.671428442, 83201.94868469238, 83201.94868469238, 83210.01530599594, 83215.09260773659, 83215.09260773659]
sent2=[83112.8299999237, 83117.9430000782, 83126.01600003242, 83137.132999897, 83145.24499988556, 83156.33899998665, 83162.43899989128, 83173.52999997139, 83183.61100006104, 83190.69499993324, 83201.80100011826, 83209.90100002289, 83214.97000002861]

## MediaPlayer+sleep()
heard2=[1219.2938978672028, 1227.3559613227844, 1238.4893853664398, 1239.4233989715576, 1246.5462560653687, 1252.5756211280823, 1256.6304965019226, 1264.731811761856, 1267.5944421291351, 1274.8348503112793, 1281.8011767864227, 1284.8629002571106, 1289.8566644191742, 1292.9728322029114, 1302.052401304245, 1304.898297071457, 1312.074850320816, 1324.225326538086, 1330.0954852104187, 1339.3116302490234, 1344.1855759620667, 1349.3431723117828, 1349.3431723117828, 1362.4653944969177]
sent2=[1227.2190001010895, 1238.3159999847412, 1246.4210000038147, 1256.49799990654, 1264.5899999141693, 1274.6989998817444, 1284.7409999370575, 1292.832999944687, 1301.9230000972748, 1311.9619998931885, 1324.0639998912811, 1339.164999961853, 1349.2130000591278, 1362.3099999427795]
heard2 = np.array(heard2) - 2
sent2 = np.array(sent2) - 2

In [361]:
distances(heard1, sent1, heard2, sent2)

,0.000000,33.281723,48.300544,62.507279,70.562767,85.604399,110.801587,124.891678
0,0.972254,0.933327,0.929484,0.902252,0.886714,0.929484,0.851713,0.851713
1,0.976138,0.937212,0.933368,0.906136,0.890599,0.933368,0.855598,0.855598
2,0.991676,0.952750,0.948906,0.921674,0.906136,0.948906,0.871136,0.871136
3,0.948865,0.909939,0.906096,0.878864,0.863326,0.906096,0.828325,0.828325
4,0.933327,0.894401,0.890558,0.863326,0.847788,0.890558,0.812787,0.812787
5,0.968328,0.929402,0.925559,0.898327,0.882789,0.925559,0.847788,0.847788
6,0.960559,0.921633,0.917790,0.890558,0.875020,0.917790,0.840019,0.840019
7,2.430552,2.391626,2.387782,2.360551,2.345013,2.387782,2.310012,2.310012
8,0.979982,0.941055,0.937212,0.909980,0.894442,0.937212,0.859441,0.859441
9,0.980022,0.941096,0.937253,0.910021,0.894483,0.937253,0.859482,0.859482
10,0.979982,0.941055,0.937212,0.909980,0.894442,0.937212,0.859441,0.859441